//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class u_comment
    {
        public int Id_Comment { get; set; }
        public int Id_Post { get; set; }
        public string Content { get; set; }
        public string Status { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Author { get; set; }
        public string Email { get; set; }
    
        public virtual u_post u_post { get; set; }
    }
}
